global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'soy-nginx-monitor'
    environment: 'docker-swarm'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Gateway nginx exporter
  - job_name: 'gateway-nginx'
    static_configs:
      - targets: ['gateway-nginx-exporter:9113']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - target_label: service
        replacement: gateway

  # MS-Exercise nginx exporter
  - job_name: 'ms-exercise-nginx'
    static_configs:
      - targets: ['ms-exercise-nginx-exporter:9114']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - target_label: service
        replacement: ms-exercise

  # MS-Other nginx exporter
  - job_name: 'ms-other-nginx'
    static_configs:
      - targets: ['ms-other-nginx-exporter:9115']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - target_label: service
        replacement: ms-other