global:
  scrape_interval: 5s  # Frequenza di raccolta metriche

scrape_configs:
  - job_name: 'locust'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.17.0.1:9646']  # Se Prometheus è in un container e Locust gira sull'host
