global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  # Locust metrics
  - job_name: 'locust'
    static_configs:
      - targets: ['host.docker.internal:9646']
    scrape_interval: 1s

  # Envoy proxy metrics - Gateway
  - job_name: 'envoy-gateway'
    static_configs:
      - targets: ['ms-stack-v5_gateway-envoy:15090']
    scrape_interval: 1s
    metrics_path: '/stats/prometheus'

  # Envoy proxy metrics - ms-exercise  
  - job_name: 'envoy-ms-exercise'
    static_configs:
      - targets: ['ms-stack-v5_ms-exercise-envoy:15090']
    scrape_interval: 1s
    metrics_path: '/stats/prometheus'

  # Envoy proxy metrics - ms-other
  - job_name: 'envoy-ms-other'
    static_configs:
      - targets: ['ms-stack-v5_ms-other-envoy:15090']
    scrape_interval: 1s
    metrics_path: '/stats/prometheus'

  # cAdvisor metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['ms-stack-v5_cadvisor:8080']
    scrape_interval: 1s

  # Node exporter metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['ms-stack-v5_node-exporter:9100']
    scrape_interval: 1s

  # Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 1s