global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'locust'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.17.0.1:9646']

  - job_name: 'traefik'
    static_configs:
      - targets: ['ms-stack-v5_traefik:8080']
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ms-stack-v5_cadvisor:8080']