#!/usr/bin/env python3
"""Generate the Envoy sidecar integration for the Online Boutique (Compose).

Lives in the SoY-locust repo (NOT inside the vendored microservices-demo/ clone),
so the proxy configs are versioned with the harness. The bench deploys with
``-f microservices-demo/docker-compose.yml -f proxy/compose.envoy.yml``; the
volume path ``../proxy/envoy/<svc>.yaml`` resolves to this directory whether
Compose bases relative paths on the project dir (microservices-demo/) or on the
override file's own dir (proxy/) — both are siblings under the repo root.

Problem it solves: the Boutique's services talk gRPC (persistent HTTP/2). A gRPC
client pins its single connection to ONE backend replica, and Compose DNS never
re-spreads it, so scaling a service adds idle replicas. Envoy load-balances per
request (STRICT_DNS resolves all replica IPs; ROUND_ROBIN spreads each request).

Emits, WITHOUT deploying anything:
  - proxy/envoy/<service>.yaml     one Envoy bootstrap per backend service
  - proxy/compose.envoy.yml        compose OVERRIDE adding the envoy-<svc> services
                                   and repointing every *_SERVICE_ADDR at its Envoy
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))          # proxy/envoy
PROXY = os.path.dirname(HERE)                              # proxy

SERVICES = {
    "productcatalogservice": 3550,
    "currencyservice": 7000,
    "cartservice": 7070,
    "recommendationservice": 8080,
    "shippingservice": 50051,
    "paymentservice": 50051,
    "emailservice": 8080,
    "adservice": 9555,
    "checkoutservice": 5050,
}

CLIENTS = {
    "frontend": {
        "PRODUCT_CATALOG_SERVICE_ADDR": "productcatalogservice",
        "CURRENCY_SERVICE_ADDR": "currencyservice",
        "CART_SERVICE_ADDR": "cartservice",
        "RECOMMENDATION_SERVICE_ADDR": "recommendationservice",
        "SHIPPING_SERVICE_ADDR": "shippingservice",
        "CHECKOUT_SERVICE_ADDR": "checkoutservice",
        "AD_SERVICE_ADDR": "adservice",
    },
    "checkoutservice": {
        "PRODUCT_CATALOG_SERVICE_ADDR": "productcatalogservice",
        "SHIPPING_SERVICE_ADDR": "shippingservice",
        "PAYMENT_SERVICE_ADDR": "paymentservice",
        "EMAIL_SERVICE_ADDR": "emailservice",
        "CURRENCY_SERVICE_ADDR": "currencyservice",
        "CART_SERVICE_ADDR": "cartservice",
    },
    "recommendationservice": {
        "PRODUCT_CATALOG_SERVICE_ADDR": "productcatalogservice",
    },
}

ENVOY_IMAGE = "envoyproxy/envoy:v1.31-latest"

ENVOY_CFG = """\
# Auto-generated by proxy/envoy/gen_envoy.py — DO NOT EDIT BY HAND.
# Envoy sidecar for `{svc}`: per-request gRPC (HTTP/2) load balancing across all
# replicas of `{svc}`. STRICT_DNS resolves EVERY replica IP from Compose DNS, and
# ROUND_ROBIN spreads each request (not each connection) across them.
admin:
  address:
    socket_address: {{ address: 0.0.0.0, port_value: 9901 }}
static_resources:
  listeners:
  - name: ingress
    address:
      socket_address: {{ address: 0.0.0.0, port_value: {port} }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: grpc_{svc}
          codec_type: AUTO
          route_config:
            name: local
            virtual_hosts:
            - name: {svc}
              domains: ["*"]
              routes:
              - match: {{ prefix: "/" }}
                route:
                  cluster: {svc}
                  timeout: 0s          # do not cap gRPC calls: app p95 can reach tens of seconds under load
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: {svc}
    connect_timeout: 1s
    type: STRICT_DNS               # resolve ALL replica IPs (LOGICAL_DNS would keep only the first)
    dns_lookup_family: V4_ONLY
    dns_refresh_rate: 5s           # re-resolve to pick up scale up / down
    respect_dns_ttl: true
    lb_policy: ROUND_ROBIN         # <-- the fix: per-request spread across replicas
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {{}}     # gRPC upstream speaks HTTP/2
    load_assignment:
      cluster_name: {svc}
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {{ address: {svc}, port_value: {port} }}
"""


def gen_envoy_configs():
    for svc, port in SERVICES.items():
        path = os.path.join(HERE, f"{svc}.yaml")
        with open(path, "w") as f:
            f.write(ENVOY_CFG.format(svc=svc, port=port))
        print("wrote", os.path.relpath(path, PROXY))


def gen_compose_override():
    lines = [
        "# Auto-generated by proxy/envoy/gen_envoy.py — DO NOT EDIT BY HAND.",
        "#",
        "# Compose OVERRIDE that puts an Envoy L7 proxy in front of every gRPC backend",
        "# so scaling actually works (per-request round-robin over HTTP/2). Apply with:",
        "#   docker compose -f microservices-demo/docker-compose.yml -f proxy/compose.envoy.yml up -d",
        "# then scale a backend, e.g.:  ... up -d --scale productcatalogservice=4",
        "# Clients keep their code: only their *_SERVICE_ADDR now point at the Envoys.",
        "",
        "services:",
        "",
        "  # --- Envoy sidecars (one per gRPC backend) --------------------------------",
    ]
    for svc, port in SERVICES.items():
        lines += [
            f"  envoy-{svc}:",
            f"    image: {ENVOY_IMAGE}",
            "    restart: unless-stopped",
            f'    command: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster", "envoy-{svc}"]',
            "    volumes:",
            f"      - ../proxy/envoy/{svc}.yaml:/etc/envoy/envoy.yaml:ro",
            "    depends_on:",
            f"      - {svc}",
            "",
        ]
    lines += ["  # --- Repoint each client's gRPC targets at the Envoys ---------------------"]
    for client, env in CLIENTS.items():
        lines += [f"  {client}:", "    environment:"]
        for var, target in env.items():
            lines.append(f'      {var}: "envoy-{target}:{SERVICES[target]}"')
        lines.append("")
    path = os.path.join(PROXY, "compose.envoy.yml")
    with open(path, "w") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print("wrote", os.path.relpath(path, PROXY))


if __name__ == "__main__":
    gen_envoy_configs()
    gen_compose_override()
    print(f"\nDone: {len(SERVICES)} Envoy sidecars, {len(CLIENTS)} clients repointed. "
          "Nothing deployed.")
