#!/usr/bin/env python3
"""Generate the nginx sidecar integration for the Online Boutique (Compose).

Lives in the SoY-locust repo (NOT inside the vendored microservices-demo/ clone).
The bench deploys with ``-f microservices-demo/docker-compose.yml -f
proxy/compose.nginx.yml``; the volume path ``../proxy/nginx/<svc>.conf`` resolves
to this directory whether Compose bases relative paths on the project dir
(microservices-demo/) or on the override file's own dir (proxy/) — both siblings.

Lighter alternative to Envoy (see ../envoy/gen_envoy.py): one nginx per gRPC
backend, per-request gRPC (HTTP/2) load balancing across the FIXED replicas.
~5x lighter than Envoy in RAM (less pollution of the energy/CPU measurement),
consistent with v5.

Caveat vs Envoy: a static `upstream { server svc; }` resolves once and pins to
the first replica IP. To spread, each nginx re-resolves via Docker's embedded DNS
(127.0.0.11) with a variable grpc_pass — DNS round-robin, no active health checks;
fine for fixed replicas under steady load, but verify the spread empirically.

Emits, WITHOUT deploying anything:
  - proxy/nginx/<service>.conf     one nginx config per backend service
  - proxy/compose.nginx.yml        compose OVERRIDE adding the nginx-<svc> services
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))          # proxy/nginx
PROXY = os.path.dirname(HERE)                              # proxy

SERVICES = {
    "productcatalogservice": 3550,
    "currencyservice": 7000,
    "cartservice": 7070,
    "recommendationservice": 8080,
    "shippingservice": 50051,
    "paymentservice": 50051,
    "emailservice": 8080,
    "adservice": 9555,
    "checkoutservice": 5050,
}

CLIENTS = {
    "frontend": {
        "PRODUCT_CATALOG_SERVICE_ADDR": "productcatalogservice",
        "CURRENCY_SERVICE_ADDR": "currencyservice",
        "CART_SERVICE_ADDR": "cartservice",
        "RECOMMENDATION_SERVICE_ADDR": "recommendationservice",
        "SHIPPING_SERVICE_ADDR": "shippingservice",
        "CHECKOUT_SERVICE_ADDR": "checkoutservice",
        "AD_SERVICE_ADDR": "adservice",
    },
    "checkoutservice": {
        "PRODUCT_CATALOG_SERVICE_ADDR": "productcatalogservice",
        "SHIPPING_SERVICE_ADDR": "shippingservice",
        "PAYMENT_SERVICE_ADDR": "paymentservice",
        "EMAIL_SERVICE_ADDR": "emailservice",
        "CURRENCY_SERVICE_ADDR": "currencyservice",
        "CART_SERVICE_ADDR": "cartservice",
    },
    "recommendationservice": {
        "PRODUCT_CATALOG_SERVICE_ADDR": "productcatalogservice",
    },
}

NGINX_IMAGE = "nginx:1.27-alpine"

NGINX_CFG = """\
# Auto-generated by proxy/nginx/gen_nginx.py — DO NOT EDIT BY HAND.
# nginx sidecar for `{svc}`: per-request gRPC (HTTP/2) load balancing across the
# replicas of `{svc}`. A variable grpc_pass + the Docker resolver re-resolves the
# service name on each request so traffic spreads over the replica IPs (a static
# `upstream {{ server {svc}; }}` would pin to the first IP).
worker_processes auto;
events {{ worker_connections 8192; }}
http {{
    access_log off;
    server {{
        listen {port};
        http2 on;                              # h2c (cleartext HTTP/2) for gRPC
        resolver 127.0.0.11 valid=5s ipv6=off; # Docker embedded DNS; re-resolve every 5s
        location / {{
            set $backend {svc}:{port};
            grpc_pass grpc://$backend;         # variable => dynamic resolution => spread across replicas
            grpc_read_timeout 3600s;           # do not cap slow gRPC calls under load
            grpc_send_timeout 3600s;
            grpc_socket_keepalive on;
        }}
    }}
}}
"""


def gen_nginx_configs():
    for svc, port in SERVICES.items():
        path = os.path.join(HERE, f"{svc}.conf")
        with open(path, "w") as f:
            f.write(NGINX_CFG.format(svc=svc, port=port))
        print("wrote", os.path.relpath(path, PROXY))


def gen_compose_override():
    lines = [
        "# Auto-generated by proxy/nginx/gen_nginx.py — DO NOT EDIT BY HAND.",
        "#",
        "# Compose OVERRIDE that puts an nginx L7 proxy in front of every gRPC backend",
        "# so scaling actually works (per-request DNS round-robin over HTTP/2). Apply with:",
        "#   docker compose -f microservices-demo/docker-compose.yml -f proxy/compose.nginx.yml up -d",
        "# then scale a backend, e.g.:  ... up -d --scale productcatalogservice=4",
        "# Clients keep their code: only their *_SERVICE_ADDR now point at the nginx sidecars.",
        "",
        "services:",
        "",
        "  # --- nginx sidecars (one per gRPC backend) --------------------------------",
    ]
    for svc, port in SERVICES.items():
        lines += [
            f"  nginx-{svc}:",
            f"    image: {NGINX_IMAGE}",
            "    restart: unless-stopped",
            "    volumes:",
            f"      - ../proxy/nginx/{svc}.conf:/etc/nginx/nginx.conf:ro",
            "    depends_on:",
            f"      - {svc}",
            "",
        ]
    lines += ["  # --- Repoint each client's gRPC targets at the nginx sidecars -------------"]
    for client, env in CLIENTS.items():
        lines += [f"  {client}:", "    environment:"]
        for var, target in env.items():
            lines.append(f'      {var}: "nginx-{target}:{SERVICES[target]}"')
        lines.append("")
    path = os.path.join(PROXY, "compose.nginx.yml")
    with open(path, "w") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print("wrote", os.path.relpath(path, PROXY))


if __name__ == "__main__":
    gen_nginx_configs()
    gen_compose_override()
    print(f"\nDone: {len(SERVICES)} nginx sidecars, {len(CLIENTS)} clients repointed. "
          "Nothing deployed.")
