version: '3.7'

services:
  # Gateway application
  gateway:
    image: icws24submission/gateway_icws24
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      - MS_EXERCISE_URL=http://ms-exercise-nginx:5001
      - MS_OTHER_URL=http://ms-other-nginx:8080
      - TRAEFIK_INTERNAL=false
      - FORCE_TRAEFIK_ROUTING=false
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 256M
    networks:
      - backend
      - monitoring
    ports:
      - "80:8080"

  ms-exercise:
    image: icws24submission/exercise_icws24
    security_opt:
      - no-new-privileges:true
    restart: always
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 256M
    networks:
      - backend

  ms-other:
    image: icws24submission/other_icws24
    security_opt:
      - no-new-privileges:true
    restart: always
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 256M
    networks:
      - backend

  postgres:
    image: registry.gitlab.com/inria-mpl/soy/msa-postgres:1.0.1
    shm_size: 1g
    security_opt:
      - no-new-privileges:true
    restart: always
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
    networks:
      - monitoring
      - backend

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--web.listen-address=:9100'
    networks:
      - monitoring
    ports:
      - 9100:9100
    deploy:
      mode: global
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--web.listen-address=:9090'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - monitoring
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring
    ports:
      - 8081:8080
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M

networks:
  monitoring:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
  prometheus_data: