version: '3.7' # Migliorata per supportare Swarm
services:
  node:
    image: gitlab.polytech.umontpellier.fr:5050/dream-team/plage/soy-v4/nodedock
    ports:
      - 5001:5001
    restart: always
    env_file:
      - /home/ubuntu/SoY-locust/sou/variables.env
    deploy:
      replicas: 1 # Puoi cambiare questo valore per il numero iniziale di repliche
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "1" # Limita le risorse
          memory: 2G
        reservations:
          cpus: "1"
          memory: 256M

  postgres:
    image: icws24submission/postgres_monolith:latest
    shm_size: 1g
    container_name: postgres
    restart: always
    env_file:
      - /home/ubuntu/SoY-locust/sou/variables.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1 # Di solito i database non vengono scalati su Swarm
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "3"
          memory: 2G
        reservations:
          cpus: "3"
          memory: 2G

volumes:
  postgres_data:
