version: '3.7' # Supporto Swarm

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --metrics.prometheus=true
      - --metrics.prometheus.addRoutersLabels=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --entrypoints.web.address=:80
      - --log.level=INFO
      - --accesslog=true
    ports:
      - "80:80"      # Traffico HTTP
      - "8080:8080"  # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
      - backend
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M

  ms-exercise:
    image: icws24submission/exercise_icws24
    security_opt:
      - no-new-privileges:true
    restart: always
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Router interno per chiamate dal gateway
        - "traefik.http.routers.ms-exercise-internal.rule=PathPrefix(`/internal/ms-exercise`)"
        - "traefik.http.routers.ms-exercise-internal.entrypoints=web"
        - "traefik.http.routers.ms-exercise-internal.tls=false"
        - "traefik.http.routers.ms-exercise-internal.service=ms-exercise"
        # Strip del prefisso /internal/ms-exercise
        - "traefik.http.routers.ms-exercise-internal.middlewares=ms-exercise-stripprefix"
        - "traefik.http.middlewares.ms-exercise-stripprefix.stripprefix.prefixes=/internal/ms-exercise"
        # Servizio backend (l'app espone 5001)
        - "traefik.http.services.ms-exercise.loadbalancer.server.port=5001"
        - "traefik.docker.network=ms-stack-v5_backend"
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 256M
    networks:
      - backend

  ms-other:
    image: icws24submission/other_icws24
    security_opt:
      - no-new-privileges:true
    restart: always
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - "traefik.enable=true"
        # Router interno per chiamate dal gateway
        - "traefik.http.routers.ms-other-internal.rule=PathPrefix(`/internal/ms-other`)"
        - "traefik.http.routers.ms-other-internal.entrypoints=web"
        - "traefik.http.routers.ms-other-internal.tls=false"
        - "traefik.http.routers.ms-other-internal.service=ms-other"
        # Strip del prefisso /internal/ms-other
        - "traefik.http.routers.ms-other-internal.middlewares=ms-other-stripprefix"
        - "traefik.http.middlewares.ms-other-stripprefix.stripprefix.prefixes=/internal/ms-other"
        # Servizio backend
        - "traefik.http.services.ms-other.loadbalancer.server.port=8080"
        - "traefik.docker.network=ms-stack-v5_backend"
    networks:
      - backend

  gateway:
    image: icws24submission/gateway_icws24
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - ms-exercise
      - ms-other
    environment:
      # Configura il gateway per usare Traefik per chiamate interne
      - MS_EXERCISE_URL=http://traefik/internal/ms-exercise
      - MS_OTHER_URL=http://traefik/internal/ms-other
      - TRAEFIK_INTERNAL=true
      - FORCE_TRAEFIK_ROUTING=true
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure  
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway.rule=Host(`localhost`) || Host(`127.0.0.1`)"
        - "traefik.http.services.gateway.loadbalancer.server.port=8080"
        - "traefik.http.routers.gateway.entrypoints=web"
        - "traefik.http.routers.gateway.tls=false"
        - "traefik.http.middlewares.gateway-headers.headers.customrequestheaders.Host=traefik"
        - "traefik.http.routers.gateway.middlewares=gateway-headers"
        - "traefik.docker.network=ms-stack-v5_monitoring"
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 256M
    networks:
      - monitoring

  postgres:
    container_name: postgres
    image: registry.gitlab.com/inria-mpl/soy/msa-postgres:1.0.1
    shm_size: 1g
    security_opt:
      - no-new-privileges:true
    restart: always
    env_file:
      - monolith-v5/variables.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--web.listen-address=:9100'
    networks:
      - monitoring
    ports:
      - 9100:9100
    deploy:
      mode: global
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--web.listen-address=:9090'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    ports:
      - 9090:9090
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring
    ports:
      - 8081:8080
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M

networks:
  monitoring:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
  prometheus_data: